<?php require_once 'modules/home/sliders.php'; ?>
<?php require_once 'modules/home/what-we-offer.php'; ?>
<?php require_once 'modules/home/projects.php'; ?>
<?php require_once 'modules/home/why-choose-us.php'; ?>
<?php require_once 'modules/home/numbers.php'; ?>
<?php require_once 'modules/home/ideation.php'; ?>
<?php //require_once 'modules/home/blog.php'; ?>
<?php require_once 'modules/home/testimonials.php'; ?>
<?php //require_once 'modules/home/connect-with-us.php'; ?>
<?php //require_once 'modules/home/partners.php'; ?>